# Generated by Django 4.1.4 on 2022-12-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_review_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
