# Generated by Django 4.1.4 on 2022-12-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_review_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
